name: Unit Tests

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: create env file
        run: |
          touch .env
          echo JIRA_USERNAME=${{ secrets.JIRA_USERNAME }} >> .env
          echo JIRA_TOKEN=${{ secrets.JIRA_TOKEN }} >> .env
          echo JIRA_HOST='coltdorsey.atlassian.net' >> .env

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
